// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuFcRXNeh07lL-SdQye-F5FawubMXZqLY',
    appId: '1:1077023138088:web:559f61fd3b1af97b18301d',
    messagingSenderId: '1077023138088',
    projectId: 'chat-app-dabf1',
    authDomain: 'chat-app-dabf1.firebaseapp.com',
    storageBucket: 'chat-app-dabf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4I_-bmaVoet3h3QPJzQtc_oGVYEKfHTw',
    appId: '1:1077023138088:android:238acfe4e14c680118301d',
    messagingSenderId: '1077023138088',
    projectId: 'chat-app-dabf1',
    storageBucket: 'chat-app-dabf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAabz1F39mCvHFTawsIp7bwg14I5iv0ok',
    appId: '1:1077023138088:ios:4a7efd4ca0b9c87a18301d',
    messagingSenderId: '1077023138088',
    projectId: 'chat-app-dabf1',
    storageBucket: 'chat-app-dabf1.appspot.com',
    iosBundleId: 'com.example.chatx',
  );
}
